name: BanManager
main: net.betterverse.BanManager
version: 1.0

commands:
   ban:
      description: Ban a player.
      usage: /ban [player] [reason]
      permission: banmanager.ban
      permission-message: You don't have banmanager.permission
   unban:
      description: Unban a player.
      usage: /unban [player]
      permission: banmanager.unban
      permission-message: You don't have banmanager.permission